methodology/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from base.views import *
from tools.views import *
from vulnerabilities.views import *

urlpatterns = [
    # re_path(r'^admin/', admin.site.urls),
    # re_path(r'^', include('cms.urls')),
    path('admin/', admin.site.urls),
    path('', frontpage, name='frontpage'),
    path('steps/', include('base.urls')),
    path('tools/', include('tools.urls')),
    path('vulnerabilities/', include('vulnerabilities.urls')),
]


tools/urls.py
from django.urls import path
from base.views import *
from .views import *

urlpatterns = [
    path('', tools, name='tools'),
    path('<int:tool_id>/', tool, name='tool'),
    path('add_tool', add_tool, name='add_tool'),
    path('<int:tool_id>/edit_tool/', edit_tool, name='edit_tool'),
    path('<int:tool_id>/delete_tool/', delete_tool, name='delete_tool'),
]

base/models.py
from django.db import models
from django.db.models.functions import Cast
from django import forms

# Create your models here.

class Step(models.Model):
    title = models.CharField(max_length=200)
    step_number = models.IntegerField(default=0)
    description = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = [
            Cast("step_number", output_field=models.IntegerField()),
        ]

class Subtask(models.Model):
    step = models.ForeignKey(Step, related_name='subtasks', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    related_tools = models.ManyToManyField('tools.Tool', related_name='subtask', null=True)
    
    def tools_list(self):
        return list(self.related_tools.all())
    def __str__(self):
        return self.title

tools/models.py
from django.db import models
from base.models import Step

# Create your models here.

class ToolTopic(models.Model):
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class Tool(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    topic = models.ForeignKey(ToolTopic, on_delete=models.SET_NULL, null=True)
    step = models.ForeignKey(Step, related_name='%(class)s_tool_related_step', on_delete=models.CASCADE, default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

vulnerabilities/models.py
from django.db import models
from base.models import *
# Create your models here.

class VulnerabilityLevel(models.IntegerChoices):
    LOW = 1, 'Low'
    MID = 2, 'Mid'
    HIGH = 3,'High'

class VulnerabilityStack(models.IntegerChoices):
    UNDEFINED = 0, 'Undefined'
    SECURITY = 1, 'Security'
    NETWORK = 2, 'Network'
    SYSTEM =  3, 'Operating System'
    DATABASE = 4, 'Database'
    SERVER = 5, 'Web Server'
    THIRD_PARTY = 6, 'Third Party Components'
    CUSTOM_WEB_APPS = 7, 'Custom Web Applications'

class Vulnerability(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    vuln_level = models.IntegerField(default=VulnerabilityLevel.MID, choices=VulnerabilityLevel.choices)
    stack = models.IntegerField(default=VulnerabilityStack.UNDEFINED, choices=VulnerabilityStack.choices, null=True)
    step = models.ForeignKey(Step, related_name='%(class)s_vuln_related_step', on_delete=models.CASCADE, default=0)
    
    def __str__(self):
        return self.title

tools/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from base.models import *

# Create your views here.

def tools(request):
    tools = Tool.objects.all()
    topics = ToolTopic.objects.all()
    step = Step.objects.all()

    if request.method == 'POST':
        title = request.POST.get('title')
        related_step = request.POST.get('related_step')
        topic_name = request.POST.get('topic')
        description = request.POST.get('description')

        if Step.objects.filter(step_number=related_step).exists():
            step = Step.objects.get(step_number=related_step)

        if ToolTopic.objects.filter(title=topic_name).exists():
            topic = ToolTopic.objects.get(title=topic_name)
        else:
            topic = ToolTopic.objects.create(title=topic_name)
        if title:
            tool = Tool.objects.create(title=title, topic=topic, step=step, description=description)
            
            return redirect('tools')
    context = {'tools':tools}
    return render(request, 'tools/tools.html', context)


def tool(request, tool_id):
    tool = get_object_or_404(Tool, pk=tool_id)
    context = {'tool':tool}
    return render(request, 'tools/tool.html', context)

def add_tool(request):
    tool = Tool.objects.all()
    steps = Step.objects.all()

    if request.method == 'POST':
        title = request.POST.get('title')
        topic = request.POST.get('topic')
        related_step = request.POST.get('related_step')
        description = request.POST.get('description')

        if Step.objects.filter(step_number=related_step).exists():
            step = Step.objects.get(step_number=related_step)

        tool = Tool.objects.create(title=title, topic=topic, step=step, description=description)
        return redirect('tools/tools.html')
    
    context = {'tool':tool, 'steps':steps}
    return render(request, 'tools/add_tool.html', context)

def edit_tool(request, tool_id):
    tool = get_object_or_404(Tool, pk=tool_id)
    step = Step.objects.all()

    if request.method == 'POST':
        title = request.POST.get('title')
        topic = request.POST.get('topic')
        related_step = request.POST.get('related_step')
        description = request.POST.get('description')

        if Step.objects.filter(step_number=related_step).exists():
            step = Step.objects.get(step_number=related_step)

        if title:
            tool.title = title
            tool.description = description
            tool.save()

        return redirect('tools')
    return render(request, 'tools/edit_tool.html', {'tool':tool})

def delete_tool(request, tool_id):
    tool = get_object_or_404(Tool, pk=tool_id)

    if request.method == 'POST':
        tool.delete()
        return redirect('/tools')
    
    return render(request, 'tools/delete_tool.html', {'tool':tool})

base/templates/base/add_step.html
{% extends 'base/base.html' %}

{% block title %}Add Step | {% endblock %}

{% block content %}

<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="#">Methodology</a></li>
        <li class="is-active"><a href="#" aria-label="page">Add Step</a></li>
    </ul>
</nav>

<div class="columns" id="step-app">
    <div class="column is-4">
        <h1 class="title">Add Step</h1>
    </div>
</div>

<div class="columns">
    <div class="column is-4">Add Step</div>
        <form action="." method="post" @submit="validateForm">
            {% csrf_token %}

            <div class="field">
                <label>Title</label>

                <div class="control">
                    <input type="text" name="title" id="id_title" v-model="title">
                </div>
            </div>

            <div class="field">
                <label>Step Number</label>

                <div class="control">
                    <input type="text" name="step_number" id="id_step_number" v-model="step_number">
                </div>
            </div>

            <div class="field">
                <label>Description</label>

                <div class="control">
                    <input type="text" name="description" id="id_description" v-model="description">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Submit</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

{% block scripts %}
<script>
    const StepApp = {
        data() {
            return {
                title: '',
                step_number: '',
                description: '',
                errors: []
            }
        },
        delimiters: ['[[,]]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if(this.title) {
                    return true
                }

                if(this.step_number) {
                    return true
                }

                if(this.description) {
                    return true
                }

                e.preventDefault()

                this.errors.push('The title is missing')

                return false
            }
        }
    }

    Vue.createApp(StepApp).mount('#step-app')
</script>

{% endblock scripts %}

tools/templates/tools/add_tool.html
{% extends 'base/base.html' %}

{% block title %}Add Tool | {% endblock %}

{% block content %}

<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="{% url 'tools'%}">Tools</a></li>
        <li class="is-active"><a href="#" aria-label="page">Add Tool</a></li>
    </ul>
</nav>

<div class="columns" id="tool-app">
    <div class="column is-4">
        <h1 class="title">Add Tool</h1>
    </div>
</div>

<div class="columns">
    <div class="column is-4">Add Tool</div>
        <form action="." method="post" @submit="validateForm">
            {% csrf_token %}

            <div class="field">
                <label>Title</label>

                <div class="control">
                    <input type="text" name="title" id="id_title" v-model="title">
                </div>
            </div>

            <div class="field">
                <label>Topic</label>

                <div class="control">
                    <input type="text" name="topic" id="id_topic", v-model="topic">
                </div>
            </div>

            <div class="field">
                <label>Related Step</label>
                <div class="control">
                    <div class="select">
                        <select name="related_step">
                            <option value="0">{{vulnerability.related_step}}</option>
                            {% for step in steps %}
                            <option value="{{forloop.counter}}">{{forloop.counter}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

            </div>

            <div class="field">
                <label>Description</label>

                <div class="control">
                    <input type="text" name="description" id="id_description" v-model="description">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Submit</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

{% block scripts %}
<script>
    const ToolApp = {
        data() {
            return {
                title: '',
                topic: '',
                related_step: '',
                description: '',
                errors: []
            }
        },
        delimiters: ['[[,]]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if(this.title) {
                    return true
                }

                if(this.topic) {
                    return true
                }

                if(this.related_step) {
                    return true
                }

                if(this.description) {
                    return true
                }

                e.preventDefault()

                this.errors.push('The title is missing')

                return false
            }
        }
    }

    Vue.createApp(ToolApp).mount('#tool-app')
</script>

{% endblock scripts %}

tools/templates/tools/delete_tool.html
{% extends 'base/base.html' %}

{% block content %}
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="{% url 'tools' %}">Tools</a></li>
        <li class="is-active"><a href="#" aria-label="page">Delete Tool</a></li>
    </ul>
</nav>

<div class="layout__body">
    <form class="form" action="" method="POST">
        {% csrf_token %}
        <div class="form__group">
            <p>Are you sure you want to delete "{{tool}}"?</p>
        </div>

        <div class="for__group">
            <div class="buttons">
                <button class="button is-danger" type="submit" value="Confirm">Confirm</button>
            </div>
        </div>
    </form>
</div>
</div>

{% endblock %}

tools/templates/tools/edit_tool.html
{% extends 'base/base.html' %}

{% block title %}Edit Tool | {% endblock %}

{% block content %}
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="{% url 'tools' %}">Tools</a></li>
        <li class="is-active"><a href="{% url 'tool' tool.id %}" aria-label="page">{{tool.title}}</a></li>
    </ul>
</nav>

<div class="columns" id="tool-app">
    <div class="column is-4">
        <h1 class="title">Edit Tool</h1>
    </div>

<div class="columns" id="tool-app">
    <form action="." method="post" @submit="validateForm">
        {% csrf_token %}

        <div class="field">
            <label>Title</label>

            <div class="control">
                <input type="text" name="title" id="id_title" v-model="title">
            </div>
        </div>

        <div class="field">
            <label>Topic</label>

            <div class="control">
                <input type="text" name="topic" id="id_topic" v-model="title">
            </div>
        </div>

        <div class="field">
            <label>Related Step</label>
            <div class="control">
                <div class="select">
                    <select name="related_step">
                        <option value="0">{{tool.step}}</option>
                        {% for step in steps %}
                        <option value="{{forloop.counter}}">{{forloop.counter}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

        </div>


        <div class="field">
            <label>Description</label>

            <div class="control">
                <input type="text" name="description" id="id_description" v-model="description">
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-success">Save Changes</button>
            </div>
        </div>
    </form>
</div>
</div>

{% endblock %}

{% block scripts %}
<script>
    const ToolApp = {
        data() {
            return {
                title: '{{tool.title}}',
                topic: '{{tool.topic}}',
                related_step: '{{tool.related_step}}',
                description: '{{tool.description}}',
                errors: []
            }
        },
        delimiters: ['[[',']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if(this.title) {
                    return true 
                }
                if(this.topic) {
                    return true
                }
                if(this.related_step) {
                    return true
                }
                if(this.description) {
                    return true
                }

                e.preventDefault()

                this.errors.push('The title is missing')

                return false
            }
        }
    }

    Vue.createApp(ToolApp).mount('#tool-app')
</script>

{% endblock %}

tools/templates/tools/tool.html
{% extends 'base/base.html' %}

{% block title %}{{tool.title}} | {% endblock %}

{% block content %}
<div id="step-app">
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'tools' %}">Tools</a></li>
            <li class="is-active"><a href="#" aria-current="page">{{ tool.title }}</a></li>
        </ul>
    </nav>

    <div class="columns">
        <div class="column">
            <h1 class="title">{{tool.title}}</h1>
            <h2 class="title">{{tool.description}}</h2>

            
            <div class="buttons">
                <a href="{% url 'edit_tool' tool.id %}" class="button is-warning">Edit Tool</a>
                <a href="{% url 'delete_tool' tool.id %}" class="button is-danger">Delete Tool</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

tools/templates/tools/tools.html
{% extends 'base/base.html' %}

{% block title %}Tools | {% endblock %}

{% block content %}

<div id="step-app">
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li class="is-active"><a href="#" aria-current="page">Tools</a></li>
        </ul>
    </nav>

    <div class="columns">
        <div class="column is-4">
            <h1 class="title">Tools</h1>

            <div class="buttons">
                <a href="{% url 'add_tool' %}" class="button is-success">Add Tool</a>
            </div>
        </div>
    </div>

    <div class="columns is-multiline">
        {% for tool in tools %}
        <div class="column is-3">
            <div class="notification">
                <h2 class="is-size-5">{{tool.title}}</h2>
                <hr>

                <a href="{% url 'tool' tool.id %}" class="button is-success">Details</a>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

vulnerabilities/templates/vulnerabilities/add_vuln.html
{% extends 'base/base.html' %}

{% block title %}Add Vulnerability | {% endblock %}

{% block content %}

<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="{% url 'vulns' %}">Vulnerabilities</a></li>
        <li class="is-active"><a href="#" aria-label="page">Add Vulnerability</a></li>
    </ul>
</nav>

<div class="columns" id="vuln-app">
    <div class="column is-4">
        <h1 class="title">Add Vulnerability</h1>
    </div>
</div>

<div class="columns">
    <div class="column is-4">Add Vulnerability</div>
        <form action="." method="post" @submit="validateForm">
            {% csrf_token %}

            <div class="field">
                <label>Title</label>

                <div class="control">
                    <input type="text" name="title" id="id_title" v-model="title">
                </div>
            </div>

            <div class="field">
                <label>Vulnerability Rating</label>
                <div class="control">
                    <div class="select">
                        <select name="vuln_rating">
                            <option value="0">{{vulnerability.vuln_level}}</option>
                            {% for rating in vuln_rating %}
                            <option value="{{forloop.counter}}">{{ forloop.counter }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <label>On Vulnerability Stack</label>
                <div class="control">
                    <div class="select">
                        <select name="vuln_stack">
                            <option value="0">{{vulnerability.vuln_stack}}</option>
                            {% for vuln_stack_option in vuln_stack %}
                            <option value="{{forloop.counter}}">{{ forloop.counter }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <label>Related Step</label>
                <div class="control">
                    <div class="select">
                        <select name="related_step">
                            <option value="0">{{vulnerability.related_step}}</option>
                            {% for step in steps %}
                            <option value="{{forloop.counter}}">{{forloop.counter}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

            </div>

            <div class="field">
                <label>Description</label>

                <div class="control">
                    <input type="text" name="description" id="id_description" v-model="description">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Submit</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

{% block scripts %}
<script>
    const VulnApp = {
        data() {
            return {
                title: '',
                rating: '',
                stack: '',
                related_step: '',
                description: '',
                errors: []
            }
        },
        delimiters: ['[[,]]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if(this.title) {
                    return true
                }

                if(this.rating) {
                    return true
                }

                if(this.stack) {
                    return true
                }

                if(this.related_step) {
                    return true
                }

                if(this.description) {
                    return true
                }

                e.preventDefault()

                this.errors.push('The title is missing')

                return false
            }
        }
    }

    Vue.createApp(VulnApp).mount('#vuln-app')
</script>

{% endblock scripts %}

vulnerabilities/templates/vulnerabilities/delete_vuln.html
{% extends 'base/base.html' %}

{% block content %}
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="{% url 'vulns' %}">Vulnerabilities</a></li>
    </ul>
</nav>

<div class="layout__body">
    <form class="form" action="" method="POST">
        {% csrf_token %}
        <div class="form__group">
            <p>Are you sure you want to delete "{{vuln}}"?</p>
        </div>

        <div class="for__group">
            <div class="buttons">
                <button class="button is-danger" type="submit" value="Confirm">Confirm</button>
            </div>
        </div>
    </form>
</div>
</div>

{% endblock %}

vulnerabilities/templates/vulnerabilities/edit_vuln.html
{% extends 'base/base.html' %}

{% block title %}Edit Vulnerability | {% endblock %}

{% block content %}
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="{% url 'vulns' %}">Vulnerabilities</a></li>
        <li class="is-active"><a href="{% url 'vuln' vuln.id %}" aria-label="page">{{vuln.title}}</a></li>
    </ul>
</nav>

<div class="columns" id="vuln-app">
    <div class="column is-4">
        <h1 class="title">Edit Vulnerability</h1>
    </div>

<div class="columns" id="vuln-app">
    <form action="." method="post" @submit="validateForm">
        {% csrf_token %}

        <div class="field">
            <label>Title</label>

            <div class="control">
                <input type="text" name="title" id="id_title" v-model="title">
            </div>
        </div>

        <div class="field">
            <label>Vulnerability Rating</label>
            <div class="control">
                <div class="select">
                    <select name="vuln_rating">
                        <option value="0">{{vulnerability.vuln_level}}</option>
                        {% for rating in vuln_rating %}
                        <option value="{{forloop.counter}}">{{ forloop.counter }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>

        <div class="field">
            <label>On Vulnerability Stack</label>
            <div class="control">
                <div class="select">
                    <select name="vuln_stack">
                        <option value="0">{{vulnerability.vuln_stack}}</option>
                        {% for vuln_stack_option in vuln_stack %}
                        <option value="{{forloop.counter}}">{{ forloop.counter }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>

        <div class="field">
            <label>Related Step</label>
            <div class="control">
                <div class="select">
                    <select name="related_step">
                        <option value="0">{{vulnerability.related_step}}</option>
                        {% for step in steps %}
                        <option value="{{forloop.counter}}">{{forloop.counter}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

        </div>

        <div class="field">
            <label>Description</label>

            <div class="control">
                <input type="text" name="description" id="id_description" v-model="description">
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-success">Submit</button>
            </div>
        </div>
    </form>
</div>
</div>

{% endblock %}

{% block scripts %}
<script>
    const VulnApp = {
        data() {
            return {
                title: '',
                rating: '',
                stack: '',
                related_step: '',
                description: '',
                errors: []
            }
        },
        delimiters: ['[[',']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if(this.title) {
                    return true
                }

                if(this.rating) {
                    return true
                }

                if(this.stack) {
                    return true
                }

                if(this.related_step) {
                    return true
                }

                if(this.description) {
                    return true
                }

                e.preventDefault()

                this.errors.push('The title is missing')

                return false
            }
        }
    }

    Vue.createApp(VulnApp).mount('#vuln-app')
</script>

{% endblock %}